---
require:
  - ndr_dev_support

# Ignore rules related to templated files
Layout/EmptyLines:
  Exclude:
    - "config/**/*.rb"

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - "config/**/*.rb"

Rails/Date:
  Enabled: false

Style/Documentation:
  Exclude:
    - "app/helpers/application_helper.rb"
    - "config/**/*.rb"

Style/GlobalStdStream:
  Exclude:
    - "config/environments/production.rb"

Style/RedundantConstantBase:
  Exclude:
    - "config/environments/production.rb"

Style/RedundantFetchBlock:
  Exclude:
    - "config/puma.rb"

Style/StringLiterals:
  Exclude:
    - "config.ru"
    - "config/**/*.rb"
    - "Rakefile"

Style/SymbolArray:
  Exclude:
    - "config/initializers/filter_parameter_logging.rb"
