---
name: "WCAG 2.1 AA "
on: [push]
# on:
#   push:
#     branches:
#       - "main"
#   pull_request:
#     branches:
#       - "main"

jobs:
  test_accessibility:
    name: Test Accessibility
    runs-on: ubuntu-latest
    # env:
    #   RACK_MINI_PROFILER: "off"
    #   RAILS_ENV: test
    #   RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
    defaults:
      run:
        working-directory: ./docs
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: Install gems and build website
        run: |
          bundle install
        # bundle exec jekyll build --trace
        # yarn install --pure-lockfile

      - name: Start server in the background
        run: |
          bundle exec jekyll serve --detach --no-watch --port 3000
        # sleep 5
        # npx http-server docs/_site/ -p 3000 &
        # curl http://127.0.0.1:3000/changelog.html -o changelog.html
        # cd docs

      # - name: Upload built webpage
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: built-page
      #     path: changelog.html

      # Run Pa11y
      - name: Run accessibility tests
        run: |
          npx pa11y --debug --standard WCAG2AA "http://127.0.0.1:3000/changelog.html"
