---
name: "WCAG 2.1 AAA "
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test_accessibility:
    name: Test Accessibility
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        # with:
        #   bundler-cache: true
        #   cache-version: <working-directory>

      # bundler-cache has issues with the working-directory
      - name: Install gems
        run: |
          bundle install

      - name: Start server in the background
        run: |
          bundle exec jekyll serve --detach --no-watch --port 3000
        # sleep 5
        # curl http://127.0.0.1:3000/changelog.html -o changelog.html

      # - name: Upload built webpage
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: built-page
      #     path: changelog.html

      # Run Pa11y
      - name: Run accessibility tests
        run: |
          npx pa11y --debug --standard WCAG2AAA "http://127.0.0.1:3000/changelog.html"
